### ISSUE TITLE
Not an issue, suggestions

### ISSUE THREAD

**Issue by tysongoulding** [lgallucci/LoonBestInSlot#11]
I love your addon, I find it very useful. I did have a few suggestions.

Instead of using BIS / Alt / Pre-raid, use a number system based on the percentage of performance.

For example: bis = 100 as in (100%)
Next best item could only be 3% less dps according to sims ranking 97 as in (97%)

I did have an idea on legendaries and make them the percentage gain going over the best "normal item" example if it's 5% gain over the top item (105) because this will not be a common attainable item.

Then it would not be too hard to calculate a BIS-Score vs GearScore.

Let me know if you have interest or.not I can provide the items/percentage scale.

**Comment by tysongoulding** [comment]
Another idea was to organize the drop down menu for class instead of spec.

Also since you are doing MIT/Threat for tanks add another menu for it.

Death Knight Blood Mitigation
Death Knight Blood Threat
Death Knight Frost
Death Knight Unholy

**Comment by lgallucci** [comment]
For the percentage (or the sim value) of the items - if you're willing to do the work to get the items/percentages for each item/spec i'm not going to turn it down.  The reason I haven't done it is it seems like a ton of work.  There are over 1500 items in the addon right now, and when phase 2 drops in a few weeks that's gonna go up to over 2100.  

The reason I've done it using the wow guides and their BIS/Alt/Preraid setups is I can just (and have) write a program to just rip all the data off the website and automatically put it in the addon.  Back in TBC I tried to do it by hand and realized it was going to take like 10 hours to go through it all.  I've considered using the sim github and programmatically go through each item in the addon and gather the data that way - but it gets really complicated with some items SIMing better with different talents or maybe SIMing great, but putting you below a stat cap that you shouldn't be.  I haven't figured a way to include all that in - and until I do ( or if you've figured it out great ) i figured people could SIM their own shit and build in a custom list if they want to.

You're not the first to suggest organizing the dropdown by class first.  That's on my list to do, but i haven't considered separating mit / threat sets into separate guides and I'm not sure how i feel about it.  I'll think some more.

Anyways, thanks for the suggestions.  I'll leave this open for a while if you want to respond.

**Comment by tysongoulding** [comment]
What data would you require?
How do you want the table?

TABLE
Item full name | Wowhead item id | class | spec | slot | percentage

**Comment by lgallucci** [comment]
Really just itemid | class | spec | percentage.  I figure if we do this, I won't replace the current system - just give the users a choice between what I have now and what you come up with.

Keep in mind that all these percentages are gonna change in like 3 weeks when phase 2 drops.  I'm not sure how you're going to manage that.

**Comment by tysongoulding** [comment]
It's on my mind, should be able to give you phases as well.
