### ISSUE TITLE
[Bug] Conflict with Broker_Everything -- _G["d"]

### ISSUE THREAD

**Issue by orionshock** [lgallucci/LoonBestInSlot#13]
"accessing undefined variable 'd',

EnchantList.lua - lines 92-95, 99, 103-106, 110
GemList.lua - lines 63-66, 70, 74,75-77,81

it's setting the global "d", also being accessed by Broker_Everything (also an error) and causing a conflict.

**Comment by orionshock** [comment]
https://github.com/HizurosWoWAddOns/Broker_Everything/issues/34

**Comment by lgallucci** [comment]
Thanks,  Yea ... I got lazy with my UI code defining variables as local.  I'll go through and try to clean that up.
