### ISSUE TITLE
Bloodbark Crusher from Bloodmoon - Feral DPS ALT BIS 

### ISSUE THREAD

**Issue by Sydaxis** [lgallucci/LoonBestInSlot#17]
odbark Crusther from Bloodmoon - Feral DPS ALT BIS is not showing as alt BIS.  This is a strange one because it is actually BIS overall when Automatic crowd pummeler is on cooldown, so you could technically add it as BIS.

**Comment by lgallucci** [comment]
I can see why, fix should be uploaded later today or tomorrow.  Thanks !
