### ISSUE TITLE
Blood DK: Hands/Feet Blood Shield ??

### ISSUE THREAD

**Issue by tylerthardy** [lgallucci/LoonBestInSlot#20]
https://github.com/lgallucci/LoonBestInSlot/blob/670ffc03cbe69e553bc51ea6ac21537f6e7762ce/LoonBestInSlot/Guides/DeathKnightBlood.lua#L29

Is this intentional? I can't find any information that has to do with head/feet and Blood Shield on the DK Discord or elsewhere.

**Comment by lgallucci** [comment]
not intentional, no.
