### ISSUE TITLE
German translation some things wrong

### ISSUE THREAD

**Issue by Parafinos** [lgallucci/LoonBestInSlot#5]
LBIS.L["PreRaid"] = "vor dem Überfall";
Everyone in Germany knows what **PreRaid** means. **Vor dem Überall** if you translate that back, its something like the meaning of  "Before the Robbery".
LBIS.L["PreRaid"] = "PreRaid";

LBIS.L["Drop"] = "Fallen";
**Fallen** also sounds wrong (to fall/traps), there is no good word for translation. Better would be just **Raid**.
Looks better with the other Dungeon Token / Profession / Raid.
LBIS.L["Drop"] = "Raid";

  LBIS.L["Loon Best In Slot"] = "Seetaucher Bester im Slot"; 
  LBIS.L["Loon Best In Slot Browser"] = "Seetaucher Bester im Slot Browser";
Seetaucher = Sea Diver, just let it be your Addon Name. The Englisch Version also works complete fine in Germany. BIS / Best In Slot is a normal thing in the Germany Community.

  LBIS.L["Loon Best In Slot"] = "Loon Best in Slot"; 
  LBIS.L["Loon Best In Slot Browser"] = "Loon Best in Slot Browser";
  LBIS.L["PvP Vendor"] = " PvP Händler";
  LBIS.L["Token"] = "Token"; 
  LBIS.L["Transmute"] = "Transmutieren";
  LBIS.L["Trash Drop"] = "Trash Drop";
  LBIS.L["World Drop"] = "Welt Drop"; can also stay World Drop

**Comment by lgallucci** [comment]
Thanks!  I'll update those.  I don't speak German (or really any of the other languages except for a bit of spanish) and was relying on others' translations and a bit of google translate.  I think i started in on german with google translate before i thought to check if other addons i had hanging around already translated some of these words.
