### ISSUE TITLE
What bis 3 and alt 3 mean?

### ISSUE THREAD

**Issue by hasnogaems** [lgallucci/LoonBestInSlot#8]
What the number mean? https://media.forgecdn.net/attachments/428/396/tooltip.png
And the abbreviation?

**Comment by lgallucci** [comment]
Alt means Alternate, the number is the phase in which the item becomes available.

**Comment by hasnogaems** [comment]
And priority goes from top to bottom?

**Comment by hasnogaems** [comment]
But what alternate really mean? It is bis but not really? It a bit worse than a bis?
